### ISSUE TITLE
Error with celluloid and sidekiq

### ISSUE THREAD

**Issue by patrick-mota** [hoardhq/hoard-app#1]
I had first an error with celluloid after running docker-compose up.
To fix that I simply removed the Gemfile.lock and it was fine. (celluloid version specified in lock wasn't available anymore)

But now when I build&docker-compose up again I have an sidekiq error complaining about redis..
web_1   | [1] - Worker 0 (pid: 8) booted, phase: 0
job_1   | Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

Can you have a look please ? I really wanted to try out your app.

**Comment by marcqualie** [comment]
Hey @patrick-mota thanks for reporting that, I was planning on resuming work on this project later this month so thanks for the jumpstart!

I've upgraded to Sidekiq 4.x which removed the celluloid dependency and bundle now works.

  Commit: https://github.com/hoardhq/hoard-app/commit/ef25b92bdf3701f2575d116ff6556be458fe9363

For the Redis issue, you need to have redis running on port 6379 locally. Since the default [Redis gem](https://github.com/redis/redis-rb) is used you can change that to whatever you want (i.e where you actually have Redis running) using the `REDIS_URL` environment variable.

**Comment by marcqualie** [comment]
@patrick-mota for reference here is the `.env` I had to create in order to get the app fully functioning with docker-compose from a blank repository:

```
REDIS_URL=redis://redis:6379
TOKEN=XXXX
SECRET_KEY_BASE=XXXXX
```

Setting the host to `redis:6379` may seem odd, but it targets the specially made links via docker-compose inside the web and job containers and will only work when the link exists and them redis container is running.

[Token and Secret Key Base](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml) are Rails dependencies and should be generated and kept secure. `docker-compose run web rake secret` is a quick way to generate these for development.

**Comment by patrick-mota** [comment]
@marcqualie Thank you very much it works now.
I just had to do what you make in your git readme:
docker-compose build
docker-compose up -> ctrl+c to exit
then to create the database/users
docker-compose run web rake db:create
docker-compose run web rake db:migrate
docker-compose run web rake db:seed

I don't know if the default user is somewhere but I had to look at postgres user table and manage to get the password too looking the table, maybe you should provide him in readme.

**Comment by marcqualie** [comment]
@patrick-mota I've updated the README with the default user details, thanks for pointing that out.

9ad471b35686bff5a2476221acc0fc74daa25139
